title: Bernarda Špoljarić # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  24, Croatia 
  <br>
  <b>Skill set:</b>
  <br>
  <b>Programming:</b>
   <br>
  - C#
  <br>
  <b>3D Modeling:</b>
   <br>
  - MakeHuman/Fuse
   <br>
  - Sweet home 3D
  <br>
  <b>Level design</b>
  <br>
  Contact email: bernarda.spoljaric1@gmail.com
  <br>
  <a href="https://www.linkedin.com/in/bernarda-%C5%A1poljari%C4%87-16468722a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
