title: Bernarda Špoljarić # your name (or website title) here
logo: # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  24, Croatia 
  <br>
  A beginner Unity Developer who has just finished Unity Education program at PISMO Novska. During education I had opportunity to work on different projects such as PC and mobile game development, level design and AR projects.
  <br>
  <b>Email:</b> bernarda.spoljaric1@gmail.com
  <br>
  <a href="https://www.linkedin.com/in/bernarda-%C5%A1poljari%C4%87-16468722a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
